# Generated by Django 2.2.7 on 2019-12-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Post', max_length=54),
        ),
    ]
